package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/hmans/beans/internal/bean"
	"github.com/hmans/beans/internal/beancore"
	"github.com/hmans/beans/internal/graph/model"
)

// MilestoneID is the resolver for the milestoneId field.
func (r *beanResolver) MilestoneID(ctx context.Context, obj *bean.Bean) (*string, error) {
	if obj.Milestone == "" {
		return nil, nil
	}
	return &obj.Milestone, nil
}

// EpicID is the resolver for the epicId field.
func (r *beanResolver) EpicID(ctx context.Context, obj *bean.Bean) (*string, error) {
	if obj.Epic == "" {
		return nil, nil
	}
	return &obj.Epic, nil
}

// FeatureID is the resolver for the featureId field.
func (r *beanResolver) FeatureID(ctx context.Context, obj *bean.Bean) (*string, error) {
	if obj.Feature == "" {
		return nil, nil
	}
	return &obj.Feature, nil
}

// Milestone is the resolver for the milestone field.
func (r *beanResolver) Milestone(ctx context.Context, obj *bean.Bean) (*bean.Bean, error) {
	if obj.Milestone == "" {
		return nil, nil
	}
	target, err := r.Core.Get(obj.Milestone)
	if err == beancore.ErrNotFound {
		return nil, nil // broken link
	}
	return target, err
}

// Epic is the resolver for the epic field.
func (r *beanResolver) Epic(ctx context.Context, obj *bean.Bean) (*bean.Bean, error) {
	if obj.Epic == "" {
		return nil, nil
	}
	target, err := r.Core.Get(obj.Epic)
	if err == beancore.ErrNotFound {
		return nil, nil // broken link
	}
	return target, err
}

// Feature is the resolver for the feature field.
func (r *beanResolver) Feature(ctx context.Context, obj *bean.Bean) (*bean.Bean, error) {
	if obj.Feature == "" {
		return nil, nil
	}
	target, err := r.Core.Get(obj.Feature)
	if err == beancore.ErrNotFound {
		return nil, nil // broken link
	}
	return target, err
}

// BlockIds is the resolver for the blockIds field.
func (r *beanResolver) BlockIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return obj.Blocks, nil
}

// RelatedIds is the resolver for the relatedIds field.
func (r *beanResolver) RelatedIds(ctx context.Context, obj *bean.Bean) ([]string, error) {
	return obj.Related, nil
}

// BlockedBy is the resolver for the blockedBy field.
func (r *beanResolver) BlockedBy(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	incoming := r.Core.FindIncomingLinks(obj.ID)
	var result []*bean.Bean
	for _, link := range incoming {
		if link.LinkType == "blocks" {
			result = append(result, link.FromBean)
		}
	}
	return result, nil
}

// Blocks is the resolver for the blocks field.
func (r *beanResolver) Blocks(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	var result []*bean.Bean
	for _, targetID := range obj.Blocks {
		if target, err := r.Core.Get(targetID); err == nil {
			result = append(result, target)
		}
	}
	return result, nil
}

// Related is the resolver for the related field.
// Bidirectional: returns both outgoing and incoming 'related' links.
func (r *beanResolver) Related(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	seen := make(map[string]bool)
	var result []*bean.Bean

	// Outgoing links
	for _, targetID := range obj.Related {
		if target, err := r.Core.Get(targetID); err == nil && !seen[target.ID] {
			seen[target.ID] = true
			result = append(result, target)
		}
	}

	// Incoming links
	for _, link := range r.Core.FindIncomingLinks(obj.ID) {
		if link.LinkType == "related" && !seen[link.FromBean.ID] {
			seen[link.FromBean.ID] = true
			result = append(result, link.FromBean)
		}
	}

	return result, nil
}

// MilestoneItems is the resolver for the milestoneItems field.
func (r *beanResolver) MilestoneItems(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	incoming := r.Core.FindIncomingLinks(obj.ID)
	var result []*bean.Bean
	for _, link := range incoming {
		if link.LinkType == "milestone" {
			result = append(result, link.FromBean)
		}
	}
	return result, nil
}

// EpicItems is the resolver for the epicItems field.
func (r *beanResolver) EpicItems(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	incoming := r.Core.FindIncomingLinks(obj.ID)
	var result []*bean.Bean
	for _, link := range incoming {
		if link.LinkType == "epic" {
			result = append(result, link.FromBean)
		}
	}
	return result, nil
}

// FeatureItems is the resolver for the featureItems field.
func (r *beanResolver) FeatureItems(ctx context.Context, obj *bean.Bean) ([]*bean.Bean, error) {
	incoming := r.Core.FindIncomingLinks(obj.ID)
	var result []*bean.Bean
	for _, link := range incoming {
		if link.LinkType == "feature" {
			result = append(result, link.FromBean)
		}
	}
	return result, nil
}

// CreateBean is the resolver for the createBean field.
func (r *mutationResolver) CreateBean(ctx context.Context, input model.CreateBeanInput) (*bean.Bean, error) {
	b := &bean.Bean{
		Slug:  bean.Slugify(input.Title),
		Title: input.Title,
		Type:  "task", // default
	}

	// Optional fields with defaults documented in schema
	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Body != nil {
		b.Body = *input.Body
	}
	if len(input.Tags) > 0 {
		b.Tags = input.Tags
	}

	if err := r.Core.Create(b); err != nil {
		return nil, err
	}

	return b, nil
}

// UpdateBean is the resolver for the updateBean field.
func (r *mutationResolver) UpdateBean(ctx context.Context, id string, input model.UpdateBeanInput) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	// Update fields if provided
	if input.Title != nil {
		b.Title = *input.Title
	}
	if input.Status != nil {
		b.Status = *input.Status
	}
	if input.Type != nil {
		b.Type = *input.Type
	}
	if input.Priority != nil {
		b.Priority = *input.Priority
	}
	if input.Body != nil {
		b.Body = *input.Body
	}
	if input.Tags != nil {
		b.Tags = input.Tags
	}

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// DeleteBean is the resolver for the deleteBean field.
func (r *mutationResolver) DeleteBean(ctx context.Context, id string) (bool, error) {
	// Verify bean exists
	_, err := r.Core.Get(id)
	if err != nil {
		return false, err
	}

	// Remove incoming links first
	if _, err := r.Core.RemoveLinksTo(id); err != nil {
		return false, err
	}

	// Delete the bean
	if err := r.Core.Delete(id); err != nil {
		return false, err
	}

	return true, nil
}

// SetMilestone is the resolver for the setMilestone field.
func (r *mutationResolver) SetMilestone(ctx context.Context, id string, target *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	if target == nil {
		b.Milestone = ""
	} else {
		b.Milestone = *target
	}

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// SetEpic is the resolver for the setEpic field.
func (r *mutationResolver) SetEpic(ctx context.Context, id string, target *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	if target == nil {
		b.Epic = ""
	} else {
		b.Epic = *target
	}

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// SetFeature is the resolver for the setFeature field.
func (r *mutationResolver) SetFeature(ctx context.Context, id string, target *string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	if target == nil {
		b.Feature = ""
	} else {
		b.Feature = *target
	}

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// AddBlock is the resolver for the addBlock field.
func (r *mutationResolver) AddBlock(ctx context.Context, id string, target string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	b.AddBlock(target)

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// RemoveBlock is the resolver for the removeBlock field.
func (r *mutationResolver) RemoveBlock(ctx context.Context, id string, target string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	b.RemoveBlock(target)

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// AddRelated is the resolver for the addRelated field.
func (r *mutationResolver) AddRelated(ctx context.Context, id string, target string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	b.AddRelated(target)

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// RemoveRelated is the resolver for the removeRelated field.
func (r *mutationResolver) RemoveRelated(ctx context.Context, id string, target string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err != nil {
		return nil, err
	}

	b.RemoveRelated(target)

	if err := r.Core.Update(b); err != nil {
		return nil, err
	}

	return b, nil
}

// Bean is the resolver for the bean field.
func (r *queryResolver) Bean(ctx context.Context, id string) (*bean.Bean, error) {
	b, err := r.Core.Get(id)
	if err == beancore.ErrNotFound {
		return nil, nil
	}
	return b, err
}

// Beans is the resolver for the beans field.
func (r *queryResolver) Beans(ctx context.Context, filter *model.BeanFilter) ([]*bean.Bean, error) {
	var beans []*bean.Bean

	// If search filter is provided, start with search results
	if filter != nil && filter.Search != nil && *filter.Search != "" {
		searchResults, err := r.Core.Search(*filter.Search)
		if err != nil {
			return nil, err
		}
		beans = searchResults
	} else {
		beans = r.Core.All()
	}

	if filter == nil {
		return beans, nil
	}

	// Apply filters
	result := beans

	// Status filters
	if len(filter.Status) > 0 {
		result = filterByField(result, filter.Status, func(b *bean.Bean) string { return b.Status })
	}
	if len(filter.ExcludeStatus) > 0 {
		result = excludeByField(result, filter.ExcludeStatus, func(b *bean.Bean) string { return b.Status })
	}

	// Type filters
	if len(filter.Type) > 0 {
		result = filterByField(result, filter.Type, func(b *bean.Bean) string { return b.Type })
	}
	if len(filter.ExcludeType) > 0 {
		result = excludeByField(result, filter.ExcludeType, func(b *bean.Bean) string { return b.Type })
	}

	// Priority filters (empty priority treated as "normal")
	if len(filter.Priority) > 0 {
		result = filterByPriority(result, filter.Priority)
	}
	if len(filter.ExcludePriority) > 0 {
		result = excludeByPriority(result, filter.ExcludePriority)
	}

	// Tag filters
	if len(filter.Tags) > 0 {
		result = filterByTags(result, filter.Tags)
	}
	if len(filter.ExcludeTags) > 0 {
		result = excludeByTags(result, filter.ExcludeTags)
	}

	// Link filters
	if len(filter.HasLinks) > 0 {
		result = filterByOutgoingLinks(result, filter.HasLinks)
	}
	if len(filter.NoLinks) > 0 {
		result = excludeByOutgoingLinks(result, filter.NoLinks)
	}
	if len(filter.LinkedAs) > 0 {
		result = filterByIncomingLinks(result, filter.LinkedAs, r.Core)
	}
	if len(filter.NoLinkedAs) > 0 {
		result = excludeByIncomingLinks(result, filter.NoLinkedAs, r.Core)
	}

	return result, nil
}

// Bean returns BeanResolver implementation.
func (r *Resolver) Bean() BeanResolver { return &beanResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type beanResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
